/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_appends_JniUtils_EffectUtil */

#ifndef _Included_com_appends_JniUtils_EffectUtil
#define _Included_com_appends_JniUtils_EffectUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_appends_JniUtils_EffectUtil
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_appends_JniUtils_EffectUtil_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_appends_JniUtils_EffectUtil
 * Method:    getResultFromJni
 * Signature: ([IIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_appends_JniUtils_EffectUtil_getResultFromJni
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
